include:
  remote: https://monitor.republicpower.net/gitlab-ci-template/docker/build.yaml

build-staging-webapp:
  extends: .container-build
  variables:
    project_name: 'rp-renci'
    container_name: 'webapp'
    container_tag: 'staging'

build-prod:
  extends: .container-build
  variables:
    project_name: 'rp-renci'
    container_name: 'webapp'
    container_tag: '$CI_COMMIT_TAG'
    dockerfile: 'Dockerfile.prod'
  only:
    - /^*-release$/

sonarcloud-check:
  stage: test 
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - master
